config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root "welcome#index"

  resources :physicians do
    resources :physician_reviews
  end

  resources :users, only: [:index]

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/physician.rb
class Physician < ApplicationRecord
  belongs_to :user, optional: true
  has_many :physician_reviews
  has_many :users, through: :physician_reviews

  validates :first_name, presence: true, allow_blank: false
  validates :last_name, presence: true, allow_blank: false

  def self.search(search)
    where("postal_code like ?", "%#{search}%")
  end

end

app/models/physician_review.rb
class PhysicianReview < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :physician

  validates :review, presence: true
  validates :rating, presence: true, :numericality => {:greater_than_or_equal_to => 1, :less_than => 7}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]

  has_many :physicians, dependent: :destroy
  has_many :physician_reviews, dependent: :destroy

  validates :first_name, presence: true, allow_blank: false
  validates :last_name, presence: true, allow_blank: false
  validates :email, presence: true, allow_blank: false

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.first_name = auth.info.first_name   # assuming the user model has a first name
      user.last_name = auth.info.last_name   # assuming the user model has a last name
      # user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def admin?
    role == "admin"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

 protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
 end

end

app/controllers/physician_reviews_controller.rb
class PhysicianReviewsController < ApplicationController
  before_action :authenticate_user!

  def edit
    @physician = Physican.find(params[:physician_id])
    @physician_review = PhysicianReview.find(params[:id])
  end

  def new
    @physician_review = PhysicianReview.new
    @physician = Physician.find(params[:physician_id])
  end

  def update
    @physician_review = PhysicianReview.find(params[:id])
    if @physician_review.update(physician_review_params)
      redirect_to physicians_path, notice: "Physician review was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @physician_review = PhysicianReview.find(params[:id])
    @physician_review.delete
    redirect_to physicians_path
    flash[:notice] = "Physician review was successfully deleted."
  end

  def create
    @physician_review = PhysicianReview.new(physician_review_params)
    @physician = Physician.find(params[:physician_id])
    @physician_review.physician = @physician
    @user = current_user
    @physician_review.user = @user

    if @physician_review.save
      flash[:notice] = "Review saved!"
      redirect_to physician_path(@physician)
    else
      flash[:errors] = "Review didn't save :-("
      render :new
    end
  end

  def authenticate_user
    if !user_signed_in?
      redirect_to new_user_session_path, notice: "You must be logged in."
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  # Never trust parameters from the scary internet, only allow the white list through.

  def physician_review_params
    params.require(:physician_review).permit(:rating, :physician_id)
  end
end

app/controllers/physicians_controller.rb
class PhysiciansController < ApplicationController
  # before_action :authenticate_user!

  def index
    @physicians = Physician.all
    if params[:search]
      @physicians = Physician.search(params[:search]).order("created_at DESC")
    else
      @physicians = Physician.all.order('created_at DESC')
    end
  end

  def edit
    @physician = Physician.find(params[:id])
  end

  def new
    @physician = Physician.new
  end

  def show
    @physician = Physician.find(params[:id])
  end

  def update
    @physician = Physician.find(params[:id])
    if @physician.update(physician_params)
      redirect_to @physician, notice: "Physician was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @physician = Physician.find(params[:id])
    @physician.delete
    redirect_to physicians_path
    flash[:notice] = "Physician was successfully deleted."
  end

  # POST /physcians
  def create
    @physician = Physician.new(physician_params)
    @physician.user = current_user

    if @physician.save
      redirect_to root_path,
      notice: 'Physician was successfully created.'
    else
      render :new
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def physician_params
    params.required(:physician).permit(:first_name, :last_name, :search)
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def facebook_email
    if request.env["omniauth.auth"].info.email.blank?
      redirect_to "/users/auth/facebook?auth_type=rerequest&scope=email"
      return # be sure to include an return if there is code after this otherwise it will be executed
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if current_user.admin?
      @users = User.all.order(email: :asc)
      @physicians = Physician.all.order(name: :asc)
      @physician_reviews = PhysicianReview.all.order(created_at: :desc)
    else
      redirect_to "/physicians"
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/physician_reviews_helper.rb
module PhysicianReviewsHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_bottom_navigation.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-12 col-md-9">
        <div class="footer-text">
          <h4 class="float-left">ME & FM Provider</h4>
          <ul class="links">
            <li class="active"><a href="#">Find A Provider</a></li>
            <li><a href="#">Sign Up</a></li>
            <li><a href="#">Sign In</a></li>
            <li><a href="#">Contact</a></li>
            <li><a href="#">ME & FM Society of BC</a></li>
          </ul>
        </div>
      </div>
      <div class="col-12 col-md-3">
        <div class="social-links float-right">
          <ul>
            <li><a href="#" class="fa fa-facebook-f"></a></li>
            <li><a href="#" class="fa fa-instagram"></a></li>
            <li><a href="#" class="fa fa-google"></a></li>
            <li><a href="#" class="fa fa-pinterest-p"></a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="copy"> Copyright © 2018. All Rights Reserved </div>
</footer>

app/views/layouts/_top_navigation.html.erb
<header class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <%= form_tag(physicians_path, :method => "get", id: "search",  class:"form-inline mr-auto search-box") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search", class: "form-control mr-sm-2" %>
        <button class="btn btn-success" type="submit"><i class="fa fa-search"></i></button>
      <% end %>

      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Find A Provider</a>
        </li>

        <% if !user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, :class => 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign In',  new_user_session_path, :class => 'nav-link'  %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Account', edit_user_registration_path, :class => 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Log Off',  destroy_user_session_path, :class => 'nav-link'  %>
          </li>
        <% end %>

        <li class="nav-item">
          <a class="nav-link" href="#">Contact</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="https://www.mefm.bc.ca/">ME & FM Society of BC</a>
        </li>
      </ul>

    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MefmApp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.0.8/css/all.css" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/bootswatch/4.0.0-beta.3/materia/bootstrap.min.css" rel="stylesheet" integrity="sha384-9+9yAZ8WTqE5Elo0puxoZtIpLRu+wf9gLMnZsiBuCThtWoy+J2LUu/PIuzzKzhhP" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="main">
      <%= render "layouts/top_navigation" %>
      <!-- <p class="notice"><%#= notice %></p>
      <p class="alert"><%#= alert %></p> -->
      <div class="alert-flash">
        <div class="alert-popup">
          <div>
            <% flash.each do |key, value| %>
              <div class="alert alert-<%= key == 'error' ? 'danger' : 'success' %> alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <%= value %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <%= yield %>
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

      <%= render "layouts/bottom_navigation" %>

    </div>

  </body>
</html>

app/views/physician_reviews/new.html.erb
  <%= form_for @physicians_review do |f| %>
  <ul>
    <li><%= f.label :rating, "Rating: " %> <%= f.select :rating,[0,1,2,3,4,5,6,7,8,9,10]  %></li>
    <li><%= f.label :review, "Review:"%> <%= f.text_box :review %> </li> f.label :street_address,'Street Address: ' %>  <%= f.text_field :street_address %></li>
    <li><%= f.hidden_field :user_id, value: current_user.id %></li>
  </ul>

    <%= f.submit "Create" %>
  <% end %>

app/views/physician_reviews/show.html.erb
<% if physician.physician_review.user == current_user || current_user.role == "admin" %>
  <%= link_to "Edit Review", edit_physician_physician_review_path %>
<% end %>

app/views/physicians/index.html.erb
<section class="physicians-bg">
  <div class="container">
    <div class="row">

      <% @physicians.each do |physician| %>
          <div class="col-12 col-md-4">
            <%= link_to physician do %>
            <div class="physician-box">
              <div class="left-img">
                <img src="/assets/profile.jpg" alt="" class="img-responsive">
                <div class="retes">
                  <i class="fa fa-star active"></i>
                  <i class="fa fa-star active"></i>
                  <i class="fa fa-star active"></i>
                  <i class="fa fa-star"></i>
                  <i class="fa fa-star"></i>
                </div>
              </div>
              <div class="box-del">
                <h4><%= physician.first_name %><%#= link_to "#{physician.first_name}" "#{physician.postal_code}", physician %></h4>
                <h5>Medical Specialists</h5>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit</p>
              </div>
            </div>
            <% end %>
          </div>
      <% end %>

    </div>
  </div>
</section>

app/views/physicians/show.html.erb
<%= button_to "Add Review", new_physician_physician_review_path(@physician) %>

app/views/welcome/index.html.erb
<section class="banner">
  <div class='container'>
    <div class="row">
      <div class="col-12 text-center">
        <div class="banner-text">
          <!-- <img src="assets/MEFMLogo.png" alt="" class="img-responsive"> -->
          <%= image_tag("MEFMLogo.png", :alt => "ME & FM Logo", class: "img-responsive") %>
          <h1>ME & FM <span>Providers</span></h1>
          <p class="text primary">Finding a medical provider who knows<span>ME & FM is hard</span></p>
          <div class="banner-search">
            <span>We make it easy</span>
            <form class="search">
              <input type="text" name="search" class="form-control" placeholder="Search By Postal Code">
              <button class="btn btn-success" type="button"><i class="fa fa-search"></i></button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="about-bg">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h2 class="text-center">What We Are About</h2>
        <div class="about-desc">
          <p>In an ideal world we would not need to create a specialised ME and FM database for physicians and other healthcare practitioners.</p>
          <p>In an ideal world, there would be an adequate number of health care professionals who are very knowledgeable about ME and FM; there would be testing and treatments, all covered by MSP.</p>
          <p>In an ideal world, there would be no stigma, no need for patients to be exposed to a health care system that more often than not treats them as malingers or psychiatric patients who just need to “push” themselves and get over it.</p>
        </div>
      </div>
    </div>
  </div>
</section>


<section class="aboutapp-bg">
  <div class="container">
    <div class="row">
      <h2 class="text-center col-12">What This App Is About</h2>
      <div class="col-12 col-lg-4">
        <div class="aboutapp-box text-center">
          <div class="icon">
            <!-- <img src="/assets/doctorlocator.png" alt="Doctor Locator" class="img-responsive"/> -->
            <%= image_tag("doctorlocator.png", :alt => "Doctor Locator", class: 'img-responsive') %>

          </div>
          <h4>Providers Close To You</h4>
          <div class="box-text">
            <p>Not every practitioner is capable of understanding and treating ME & FM. We help find the closest one to you based on your postal code.</p>
            <p>No more wasting time and calling numerous practices and clinics. Find a practitioner in 30 seconds!</p>
          </div>
        </div>
      </div>
      <div class="col-12 col-lg-4">
        <div class="aboutapp-box text-center">
          <div class="icon">
            <!-- <img src="/assets/review.png" alt="Review" class="img-responsive"/> -->
            <%= image_tag("review.png", :alt => "Review", class: 'img-responsive') %>

          </div>
          <h4>Review Providers</h4>
          <div class="box-text">
            <p>Rate and review. Review the practitioners you do visit, and rate them on a variety of important factors.</p>
            <p>It's more than being knowledgeable. It's about bedside manner and creating support systems that you can count on.</p>
          </div>
        </div>
      </div>
      <div class="col-12 col-lg-4">
        <div class="aboutapp-box text-center">
          <div class="icon">
            <!-- <img src="/assets/openheart.png" alt="Open Heart" class="img-responsive"/> -->
            <%= image_tag("openheart.png", :alt => "Open Heart", class: 'img-responsive') %>
          </div>
          <h4>Help Others</h4>
          <div class="box-text">
            <p>With your ratings and reviews, you also help your community.</p>
            <p> With 17 million people affected worldwide, you can help them find a practiioner that can get them started on a path to treatment and a happier life.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>